// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Services() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"services\" class=\"py-5 bg-light\"><div class=\"container\"><h2 class=\"text-center mb-5 display-6 fw-bold\">Наша продукция</h2><div class=\"row g-4\"><div class=\"col-md-4\"><div class=\"card h-100 border-0 shadow-sm service-card\"><div class=\"card-body text-center p-4\"><i class=\"bi bi-droplet display-4 text-primary mb-3\"></i><h5 class=\"card-title\">Анаэробные клеи</h5><p class=\"card-text text-muted\">Фиксация и герметизация резьбовых соединений, втулок, подшипников.</p></div></div></div><div class=\"col-md-4\"><div class=\"card h-100 border-0 shadow-sm service-card\"><div class=\"card-body text-center p-4\"><i class=\"bi bi-tools display-4 text-primary mb-3\"></i><h5 class=\"card-title\">Цианоакрилатные клеи</h5><p class=\"card-text text-muted\">Мгновенное склеивание металлов, пластиков, резины и кожи.</p></div></div></div><div class=\"col-md-4\"><div class=\"card h-100 border-0 shadow-sm service-card\"><div class=\"card-body text-center p-4\"><i class=\"bi bi-paint-bucket display-4 text-primary mb-3\"></i><h5 class=\"card-title\">Эпоксидные составы</h5><p class=\"card-text text-muted\">Высокопрочные двухкомпонентные клеи для ремонта и восстановления деталей.</p></div></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
