// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Services() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"services\" class=\"py-5 bg-light\"><div class=\"container\"><h2 class=\"text-center mb-4\">Наши услуги</h2><div class=\"row g-4\"><div class=\"col-md-4\"><div class=\"card border-0 shadow-sm h-100 text-center p-4\"><div class=\"card-body\"><i class=\"bi bi-laptop display-6 text-primary\"></i><!-- если добавить иконки Bootstrap Icons локально --><h5 class=\"card-title mt-3\">Веб-разработка</h5><p class=\"card-text text-muted\">Создание современных адаптивных сайтов.</p></div></div></div><div class=\"col-md-4\"><div class=\"card border-0 shadow-sm h-100 text-center p-4\"><div class=\"card-body\"><i class=\"bi bi-phone display-6 text-primary\"></i><h5 class=\"card-title mt-3\">Мобильные приложения</h5><p class=\"card-text text-muted\">Нативные и кроссплатформенные решения.</p></div></div></div><div class=\"col-md-4\"><div class=\"card border-0 shadow-sm h-100 text-center p-4\"><div class=\"card-body\"><i class=\"bi bi-graph-up display-6 text-primary\"></i><h5 class=\"card-title mt-3\">Аналитика</h5><p class=\"card-text text-muted\">Данные для принятия стратегических решений.</p></div></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
